# -*- coding: utf-8 -*-
"""应用方案PDF生成器：解析 应用方案-PDF内容.md（20页结构）→ ReportLab排版 → 封面合并。

用法：py -3 scripts/build_application_pdf.py
输出：应用方案-健康事件涟漪守护智能体.pdf（封面+正文，≤20页）

注意：本文件必须保持UTF-8编码；不要对本脚本运行 code.sanitize（会破坏非ASCII字符）。
页面分隔符采用 unicode 转义写法（U+2550 ═），任何编码层都不会破坏它。
"""
import io
import os
import re
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak, Image, KeepTogether, PageBreak, Paragraph,
    SimpleDocTemplate, Spacer, Table, TableStyle,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MD_PATH = os.path.join(ROOT, "应用方案-PDF内容.md")
BODY_PDF = os.path.join(ROOT, "build", "application_body.pdf")
FINAL_PDF = os.path.join(ROOT, "应用方案-健康事件涟漪守护智能体.pdf")
IMG_OVERVIEW = os.path.join(ROOT, "docs-assets", "console-overview.png")
IMG_EVIDENCE = os.path.join(ROOT, "docs-assets", "console-evidence-mdt.png")

# 页面分隔标记（防御性写法：U+2550 ═ ×3+ + 第X页）
PAGE_SEP_RE = re.compile("\u2550{3,}\\s*第(\\d+)页\\s*\u2550{3,}")

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
TABLE_STRIPE = colors.HexColor('#ebedee')
HEADER_FILL = colors.HexColor('#334250')
BORDER = colors.HexColor('#b8c4cf')
TEXT_PRIMARY = colors.HexColor('#1a1b1c')
TEXT_MUTED = colors.HexColor('#6f7378')
SEM_INFO = colors.HexColor('#466a8e')

# ── 字体注册（Windows 微软雅黑） ──
pdfmetrics.registerFont(TTFont('MSYH', 'C:/Windows/Fonts/msyh.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('MSYHBD', 'C:/Windows/Fonts/msyhbd.ttc', subfontIndex=0))
pdfmetrics.registerFont(TTFont('CONSOLA', 'C:/Windows/Fonts/consola.ttf'))
registerFontFamily('MSYH', normal='MSYH', bold='MSYHBD')
registerFontFamily('CONSOLA', normal='CONSOLA', bold='CONSOLA')

PAGE_W, PAGE_H = A4
MARGIN = 1.7 * cm
AVAIL_W = PAGE_W - 2 * MARGIN

EMOJI_RE = re.compile(
    "[\U0001F000-\U0001FAFF\U00002600-\U000027BF\U0001F900-\U0001F9FF\u2705\u274c\u2714\u2716\u26a0]")


def inline(text: str) -> str:
    """行内 markdown → ReportLab 标记。"""
    text = EMOJI_RE.sub("", text)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    text = text.replace("`", "")
    return text.strip()


def build_styles():
    return {
        "h2": ParagraphStyle("H2", fontName="MSYHBD", fontSize=15.5, leading=22,
                             textColor=HEADER_FILL, spaceBefore=16, spaceAfter=6, wordWrap="CJK"),
        "h3": ParagraphStyle("H3", fontName="MSYHBD", fontSize=12.5, leading=17.5,
                             textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=4, wordWrap="CJK"),
        "body": ParagraphStyle("Body", fontName="MSYH", fontSize=11, leading=18,
                               textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=5, wordWrap="CJK"),
        "bullet": ParagraphStyle("Bullet", fontName="MSYH", fontSize=11, leading=18,
                                 textColor=TEXT_PRIMARY, leftIndent=12, spaceAfter=4, wordWrap="CJK"),
        "code": ParagraphStyle("Code", fontName="MSYH", fontSize=9, leading=13,
                               textColor=SEM_INFO, backColor=TABLE_STRIPE, borderPadding=5,
                               leftIndent=8, spaceBefore=4, spaceAfter=6, wordWrap="CJK"),
        "caption": ParagraphStyle("Caption", fontName="MSYH", fontSize=9, leading=12,
                                  textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=2, spaceAfter=8),
        "th": ParagraphStyle("TH", fontName="MSYHBD", fontSize=9.8, leading=13.4,
                             textColor=colors.white, alignment=TA_CENTER, wordWrap="CJK"),
        "td": ParagraphStyle("TD", fontName="MSYH", fontSize=9.8, leading=13.4,
                             textColor=TEXT_PRIMARY, alignment=TA_LEFT, wordWrap="CJK"),
    }


def make_table(rows, styles):
    header = rows[0]
    body = rows[1:]
    n_cols = len(header)
    if n_cols == 2:
        ratios = [0.26, 0.74]
    elif n_cols == 3:
        ratios = [0.22, 0.39, 0.39]
    else:
        ratios = [1.0 / n_cols] * n_cols
    col_widths = [r * AVAIL_W for r in ratios]

    data = [[Paragraph("<b>%s</b>" % inline(c), styles["th"]) for c in header]]
    for row in body:
        row = (row + [""] * n_cols)[:n_cols]
        data.append([Paragraph(inline(c), styles["td"]) for c in row])

    table = Table(data, colWidths=col_widths, hAlign="CENTER", repeatRows=1)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), HEADER_FILL),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    for i in range(1, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), TABLE_STRIPE))
    table.setStyle(TableStyle(style_cmds))
    return table


def parse_page(block: str):
    """解析单页 markdown → flowable 描述元组列表。"""
    flows = []
    lines = block.splitlines()
    i = 0
    table_buf = []
    while i < len(lines):
        line = lines[i].rstrip()
        is_table = line.startswith("|") and line.endswith("|")
        if is_table:
            cells = [c.strip() for c in line.strip("|").split("|")]
            if not all(re.fullmatch(r":?-{3,}:?", c) for c in cells):
                table_buf.append(cells)
            i += 1
            continue
        if table_buf:
            flows.append(("table", table_buf))
            table_buf = []
        if not line.strip() or line.strip() == "---":
            i += 1
            continue
        if line.startswith("### "):
            flows.append(("h3", line[4:].strip()))
        elif line.startswith("## "):
            flows.append(("h2", line[3:].strip()))
        elif line.startswith("# "):
            flows.append(("h2", line[2:].strip()))
        elif line.startswith("> "):
            flows.append(("body", line[2:].strip()))
        elif line.startswith("- "):
            flows.append(("bullet", line[2:].strip()))
        elif line.startswith("```"):
            code_buf = []
            i += 1
            while i < len(lines) and not lines[i].startswith("```"):
                code_buf.append(lines[i])
                i += 1
            flows.append(("code", "\n".join(code_buf)))
        elif re.match(r"^\d+\. ", line):
            flows.append(("bullet", line))
        else:
            flows.append(("body", line.strip()))
        i += 1
    if table_buf:
        flows.append(("table", table_buf))
    return flows


def page_flows(story, block, styles, images=None):
    count = 0
    for kind, payload in parse_page(block):
        count += 1
        if kind == "h2":
            story.append(CondPageBreak(PAGE_H * 0.12))
            story.append(Paragraph("<b>%s</b>" % inline(payload), styles["h2"]))
        elif kind == "h3":
            story.append(Paragraph("<b>%s</b>" % inline(payload), styles["h3"]))
        elif kind == "body":
            story.append(Paragraph(inline(payload), styles["body"]))
        elif kind == "bullet":
            text = inline(payload)
            if not text.startswith("•"):
                text = "• " + text
            story.append(Paragraph(text, styles["bullet"]))
        elif kind == "code":
            for ln in payload.splitlines() or [""]:
                story.append(Paragraph(inline(ln) if ln.strip() else "&nbsp;", styles["code"]))
        elif kind == "table":
            story.append(Spacer(1, 3))
            story.append(make_table(payload, styles))
            story.append(Spacer(1, 5))
    if images:
        for path, caption in images:
            if not os.path.exists(path):
                continue
            from PIL import Image as PILImage
            with PILImage.open(path) as pil:
                ow, oh = pil.size
            max_w, max_h = AVAIL_W, PAGE_H * 0.34
            ratio = min(max_w / ow, max_h / oh, 1.0)
            story.append(Spacer(1, 4))
            story.append(KeepTogether([
                Image(path, width=ow * ratio, height=oh * ratio),
                Paragraph(caption, styles["caption"]),
            ]))
    return count


def build_body():
    os.makedirs(os.path.dirname(BODY_PDF), exist_ok=True)
    src = io.open(MD_PATH, encoding="utf-8").read()
    parts = PAGE_SEP_RE.split(src)
    pages = {}
    for i in range(1, len(parts), 2):
        pages[int(parts[i])] = parts[i + 1]
    if not pages:
        raise SystemExit("FATAL: 页面分隔标记解析失败，请检查MD文件的编码与分隔符")

    styles = build_styles()
    story = []
    total_flows = 0
    for page_no in range(2, 21):
        block = pages.get(page_no, "")
        images = None
        if page_no == 9 and os.path.exists(IMG_OVERVIEW):
            images = [(IMG_OVERVIEW, "图1：涟漪守护指挥中心——五维涟漪图谱与RII强度总览（真实系统截图，在线推演模式）")]
        if page_no == 15 and os.path.exists(IMG_EVIDENCE):
            images = [(IMG_EVIDENCE, "图2：反事实护栏红锁审计、哈希链证据与五Agent MDT会诊（真实系统截图）")]
        total_flows += page_flows(story, block, styles, images)

    doc = SimpleDocTemplate(
        BODY_PDF, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN, topMargin=1.5 * cm, bottomMargin=1.6 * cm,
        title="应用方案：健康事件涟漪守护智能体", author="智慧云脑团队", creator="智慧云脑团队",
        subject="2026 iCAN大学生创新创业大赛 AI无代码智能体挑战赛 参赛作品应用方案",
    )
    doc.build(story)
    print("body flowables=%d, md pages parsed=%d" % (total_flows, len(pages)))


def render_cover():
    sys.path.insert(0, r"C:\Users\联想\.zcode\cli\plugins\cache\zcode-plugins-official\document-skills\0.1.4\skills\pdf\scripts")
    from cover_render import detect_fonts, render_cover

    fonts = detect_fonts()
    content = {
        "kicker": "2026 iCAN大学生创新创业大赛 · AI无代码智能体挑战赛（DuMate赛题）",
        "hero": "健康事件涟漪守护智能体",
        "summary": "当新诊断、新处方、异常指标发生，智能体主动推演该事件在患者生活中的多维连锁影响："
                   "药物-生活冲突、复查窗口、并发症信号、家属注意事项、时间学触达。"
                   "涟漪强度指数RII量化每一重影响，反事实护栏锁定高危路径，哈希链证据可导出HL7 FHIR标准。",
        "meta": "参赛团队：智慧云脑团队 · 应用方案",
        "footer": "HEALTH RIPPLE AGENT · SMART CLOUD BRAIN",
        "year": "2026",
        "word": "iCAN 2026",
    }
    palette = {"primary": "#334250", "text": "#1a1b1c", "muted": "#6f7378", "bg": "#ffffff",
               "accent": "#2a8787"}
    cover_pdf = os.path.join(ROOT, "build", "cover.pdf")
    render_cover("05", content, cover_pdf, palette=palette, fonts=fonts)
    return cover_pdf


def merge(cover_pdf):
    from pypdf import PdfReader, PdfWriter, Transformation

    A4_W, A4_H = 595.28, 841.89

    def normalize(page):
        box = page.mediabox
        w, h = float(box.width), float(box.height)
        if abs(w - A4_W) > 2 or abs(h - A4_H) > 2:
            page.add_transformation(Transformation().scale(sx=A4_W / w, sy=A4_H / h))
            page.mediabox.lower_left = (0, 0)
            page.mediabox.upper_right = (A4_W, A4_H)
        return page

    writer = PdfWriter()
    writer.add_page(normalize(PdfReader(cover_pdf).pages[0]))
    for page in PdfReader(BODY_PDF).pages:
        writer.add_page(normalize(page))
    writer.add_metadata({
        "/Title": "应用方案：健康事件涟漪守护智能体",
        "/Author": "智慧云脑团队",
        "/Creator": "智慧云脑团队",
        "/Subject": "2026 iCAN大学生创新创业大赛 AI无代码智能体挑战赛 参赛作品应用方案",
    })
    with open(FINAL_PDF, "wb") as f:
        writer.write(f)


def main():
    build_body()
    cover_pdf = render_cover()
    merge(cover_pdf)
    from pypdf import PdfReader
    n = len(PdfReader(FINAL_PDF).pages)
    size_kb = os.path.getsize(FINAL_PDF) // 1024
    print("DONE pages=%d size=%dKB -> %s" % (n, size_kb, FINAL_PDF))
    if n > 20:
        print("WARN: 超过20页，需要缩小字号重排")
        sys.exit(2)


if __name__ == "__main__":
    main()
