SET client_encoding = 'UTF8';

CREATE TABLE IF NOT EXISTS patient (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  gender VARCHAR(10),
  age INT,
  allergy_history VARCHAR(500),
  past_history VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS department (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL UNIQUE,
  description VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS doctor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  phone VARCHAR(20) UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  department_id BIGINT NOT NULL,
  title VARCHAR(50),
  specialty VARCHAR(500),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS triage_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  chief_complaint TEXT NOT NULL,
  recommended_department VARCHAR(100),
  recommended_doctor_ids VARCHAR(255),
  assigned_doctor_id BIGINT,
  reason TEXT,
  ai_result_json TEXT,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE triage_record ADD COLUMN IF NOT EXISTS assigned_doctor_id BIGINT;

CREATE TABLE IF NOT EXISTS doctor_schedule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  time_range VARCHAR(30) NOT NULL,
  capacity INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointment_slot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id BIGINT,
  doctor_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  capacity INT NOT NULL,
  remaining_capacity INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_schedule_suggestion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  time_range VARCHAR(30) NOT NULL,
  capacity INT NOT NULL,
  reason TEXT,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS registration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  triage_record_id BIGINT,
  slot_id BIGINT,
  appointment_time TIMESTAMP NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medical_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  registration_id BIGINT NOT NULL UNIQUE,
  chief_complaint TEXT NOT NULL,
  present_illness TEXT,
  past_history TEXT,
  physical_exam TEXT,
  diagnosis TEXT NOT NULL,
  treatment_advice TEXT,
  ai_generated BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  medical_record_id BIGINT,
  registration_id BIGINT,
  risk_level VARCHAR(20),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL,
  drug_name VARCHAR(100) NOT NULL,
  dosage VARCHAR(100) NOT NULL,
  frequency VARCHAR(100) NOT NULL,
  usage_method VARCHAR(200) NOT NULL,
  days INT,
  remark VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE registration ADD COLUMN IF NOT EXISTS slot_id BIGINT;
ALTER TABLE prescription ADD COLUMN IF NOT EXISTS registration_id BIGINT;
ALTER TABLE prescription_item ADD COLUMN IF NOT EXISTS days INT;
ALTER TABLE prescription_item ADD COLUMN IF NOT EXISTS remark VARCHAR(500);

CREATE TABLE IF NOT EXISTS prescription_check_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT,
  patient_id BIGINT NOT NULL,
  doctor_id BIGINT NOT NULL,
  risk_level VARCHAR(20) NOT NULL,
  suggestions TEXT,
  interactions TEXT,
  ai_result_json TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notification_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- doctor_id 可空：患者向守护通知（涟漪推演 ripple.derived / 随访触达）按 patient_id 投递，无医生归属
  doctor_id BIGINT,
  patient_id BIGINT,
  prescription_id BIGINT,
  type VARCHAR(50) NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  risk_level VARCHAR(20),
  read_status VARCHAR(20) NOT NULL DEFAULT 'UNREAD',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_template (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(50) NOT NULL,
  department_code VARCHAR(50),
  template_name VARCHAR(100) NOT NULL,
  template_content TEXT NOT NULL,
  output_schema TEXT,
  version VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_generation_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_type VARCHAR(50) NOT NULL,
  provider VARCHAR(50),
  model VARCHAR(100),
  request_id VARCHAR(64),
  biz_id BIGINT,
  patient_id BIGINT,
  doctor_id BIGINT,
  prompt_template_id BIGINT,
  input_summary TEXT,
  output_summary TEXT,
  success BOOLEAN,
  latency_ms BIGINT,
  request_summary TEXT,
  response_summary TEXT,
  raw_result_json TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN',
  error_message TEXT,
  duration_ms INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS provider VARCHAR(50);
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS model VARCHAR(100);
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS request_id VARCHAR(64);
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS input_summary TEXT;
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS output_summary TEXT;
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS success BOOLEAN;
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'UNKNOWN';
UPDATE ai_generation_log SET status = 'UNKNOWN' WHERE status IS NULL;
ALTER TABLE ai_generation_log ALTER COLUMN status SET DEFAULT 'UNKNOWN';
ALTER TABLE ai_generation_log ALTER COLUMN status SET NOT NULL;
ALTER TABLE ai_generation_log ADD COLUMN IF NOT EXISTS latency_ms BIGINT;
CREATE INDEX IF NOT EXISTS idx_ai_log_request_id ON ai_generation_log(request_id);
CREATE INDEX IF NOT EXISTS idx_ai_log_task_created ON ai_generation_log(task_type, created_at);

CREATE TABLE IF NOT EXISTS outbox_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(64) NOT NULL UNIQUE,
  event_type VARCHAR(80) NOT NULL,
  source_service VARCHAR(80) NOT NULL,
  routing_key VARCHAR(120) NOT NULL,
  payload_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  next_retry_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_error TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drug (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  specification VARCHAR(100),
  contraindication TEXT,
  interaction_rule TEXT,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_entry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  symptoms TEXT NOT NULL,
  risk_signals TEXT,
  advice TEXT NOT NULL,
  department_code VARCHAR(50),
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_dict (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dict_type VARCHAR(50) NOT NULL,
  dict_key VARCHAR(50) NOT NULL,
  dict_value VARCHAR(100) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS followup_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  diagnosis VARCHAR(255),
  medications TEXT,
  followup_days INT DEFAULT 7,
  followup_date VARCHAR(20),
  reminder_schedule TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS followup_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id BIGINT NOT NULL,
  status VARCHAR(50) NOT NULL,
  notes TEXT,
  abnormal BOOLEAN DEFAULT FALSE,
  doctor_notified BOOLEAN DEFAULT FALSE,
  submitted_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_followup_record_plan FOREIGN KEY (plan_id) REFERENCES followup_plan(id)
);

CREATE INDEX IF NOT EXISTS idx_registration_patient_status ON registration(patient_id, status);
CREATE INDEX IF NOT EXISTS idx_registration_doctor_status ON registration(doctor_id, status);
CREATE INDEX IF NOT EXISTS idx_registration_slot_status ON registration(slot_id, status);
CREATE INDEX IF NOT EXISTS idx_triage_patient_status ON triage_record(patient_id, status);
CREATE INDEX IF NOT EXISTS idx_triage_assigned_doctor ON triage_record(assigned_doctor_id, status);
CREATE INDEX IF NOT EXISTS idx_schedule_work_date ON doctor_schedule(work_date, status);
CREATE INDEX IF NOT EXISTS idx_slot_start_status ON appointment_slot(start_time, status);
CREATE INDEX IF NOT EXISTS idx_medical_record_patient ON medical_record(patient_id);
CREATE INDEX IF NOT EXISTS idx_prescription_patient ON prescription(patient_id);
CREATE INDEX IF NOT EXISTS idx_prescription_doctor ON prescription(doctor_id);
CREATE INDEX IF NOT EXISTS idx_prescription_registration ON prescription(registration_id);
CREATE INDEX IF NOT EXISTS idx_notification_doctor_status ON notification_message(doctor_id, read_status);
CREATE INDEX IF NOT EXISTS idx_outbox_status_retry ON outbox_event(status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_drug_status ON drug(status);
CREATE INDEX IF NOT EXISTS idx_knowledge_status_department ON knowledge_entry(status, department_code);
CREATE INDEX IF NOT EXISTS idx_system_dict_type ON system_dict(dict_type, status);
CREATE INDEX IF NOT EXISTS idx_followup_plan_patient ON followup_plan(patient_id);
CREATE INDEX IF NOT EXISTS idx_followup_record_plan ON followup_record(plan_id);

-- ==================== 涟漪守护（ripple-service）====================
-- 知识库规则表
CREATE TABLE IF NOT EXISTS drug_lifestyle_conflict (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  drug_keyword VARCHAR(100) NOT NULL,
  conflict_item VARCHAR(100) NOT NULL,
  risk_description TEXT,
  severity VARCHAR(20) NOT NULL,
  advice TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dlc_drug ON drug_lifestyle_conflict(drug_keyword);

CREATE TABLE IF NOT EXISTS complication_signal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_keyword VARCHAR(100) NOT NULL,
  signal_symptom VARCHAR(255) NOT NULL,
  complication VARCHAR(255),
  action_advice VARCHAR(255),
  urgency VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cs_diagnosis ON complication_signal(diagnosis_keyword);

CREATE TABLE IF NOT EXISTS recheck_window (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_keyword VARCHAR(100) NOT NULL,
  item VARCHAR(255) NOT NULL,
  timing VARCHAR(100) NOT NULL,
  chrono_type VARCHAR(20) NOT NULL,
  advice TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rw_diagnosis ON recheck_window(diagnosis_keyword);

CREATE TABLE IF NOT EXISTS chrono_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diagnosis_keyword VARCHAR(100) NOT NULL,
  chrono_type VARCHAR(20) NOT NULL,
  event VARCHAR(255) NOT NULL,
  trigger_time VARCHAR(100),
  action VARCHAR(255),
  start_hour INT,
  offset_days INT,
  period_days INT,
  target_month INT,
  evidence_basis VARCHAR(500),
  miss_cost VARCHAR(500),
  evidence_level VARCHAR(30),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cr_diagnosis ON chrono_rule(diagnosis_keyword);

-- 运行时表
CREATE TABLE IF NOT EXISTS ripple_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  diagnosis VARCHAR(255),
  drugs_json TEXT,
  past_history VARCHAR(1000),
  ripple_graph_json TEXT,
  total_nodes INT,
  high_risk_count INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_re_patient ON ripple_event(patient_id);

CREATE TABLE IF NOT EXISTS counterfactual_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id VARCHAR(100) NOT NULL UNIQUE,
  decision_type VARCHAR(50) NOT NULL,
  patient_id BIGINT,
  chosen_path TEXT,
  alternative_paths_json TEXT,
  inputs_json TEXT,
  considered_factors_json TEXT,
  decision_json TEXT,
  confidence DECIMAL(5,4),
  action_taken VARCHAR(100),
  agent_id VARCHAR(100),
  hash VARCHAR(64),
  prev_hash VARCHAR(64),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ce_type ON counterfactual_evidence(decision_type);
CREATE INDEX IF NOT EXISTS idx_ce_patient ON counterfactual_evidence(patient_id);

CREATE TABLE IF NOT EXISTS chrono_trigger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL,
  ripple_event_id BIGINT,
  chrono_type VARCHAR(20) NOT NULL,
  event VARCHAR(255) NOT NULL,
  trigger_time VARCHAR(100),
  next_trigger_at TIMESTAMP,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  action VARCHAR(255),
  evidence_basis VARCHAR(500),
  miss_cost VARCHAR(500),
  evidence_level VARCHAR(30),
  last_fired_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ct_patient ON chrono_trigger(patient_id);
CREATE INDEX IF NOT EXISTS idx_ct_due ON chrono_trigger(status, next_trigger_at);

CREATE TABLE IF NOT EXISTS mdt_consultation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mdt_id VARCHAR(50) NOT NULL UNIQUE,
  patient_id BIGINT,
  chief_complaint VARCHAR(500),
  past_history_json TEXT,
  diagnosis VARCHAR(255),
  drugs_json TEXT,
  consultation_json TEXT,
  consensus_json TEXT,
  agent_count INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_mdt_patient ON mdt_consultation(patient_id);

-- 涟漪知识库种子（幂等：表空才写入，与服务端 KnowledgeBaseSeeder 语义一致）
INSERT INTO drug_lifestyle_conflict (drug_keyword, conflict_item, risk_description, severity, advice)
SELECT * FROM (VALUES
  ('二甲双胍', '饮酒', '乳酸酸中毒（严重可致死）', 'HIGH', '服药期间禁止饮酒'),
  ('二甲双胍', '维生素B12缺乏', '长期服用致B12缺乏性贫血', 'MEDIUM', '建议定期监测B12水平'),
  ('二甲双胍', '造影剂联用', '肾损伤', 'HIGH', '造影检查前需提前停药48小时'),
  ('华法林', '柚子/葡萄柚', '增强抗凝效果，出血风险', 'HIGH', '服药期间禁止食用柚子'),
  ('华法林', '大量绿叶蔬菜', '降低抗凝效果，血栓风险', 'MEDIUM', '保持稳定摄入量，勿突然增减'),
  ('阿莫西林', '饮酒', '双硫仑样反应', 'MEDIUM', '服药期间及停药后7天避免饮酒'),
  ('布洛芬', '饮酒', '胃肠道出血', 'HIGH', '服药期间禁止饮酒'),
  ('布洛芬', '空腹服用', '胃黏膜损伤', 'MEDIUM', '建议餐后服用'),
  ('他汀类', '柚子/葡萄柚', '肌病/横纹肌溶解风险', 'HIGH', '服药期间禁止食用柚子'),
  ('头孢类', '饮酒', '双硫仑样反应（严重可致死）', 'HIGH', '服药期间及停药后7-10天禁止饮酒'),
  ('磺脲类降糖药', '饮酒', '低血糖/双硫仑反应', 'HIGH', '服药期间禁止饮酒'),
  ('四环素', '日晒', '光敏反应', 'MEDIUM', '服药期间避免强烈日晒'),
  ('甲氨蝶呤', '饮酒', '肝损伤加重', 'HIGH', '服药期间禁止饮酒')
) AS seed(drug_keyword, conflict_item, risk_description, severity, advice)
WHERE NOT EXISTS (SELECT 1 FROM drug_lifestyle_conflict);

INSERT INTO complication_signal (diagnosis_keyword, signal_symptom, complication, action_advice, urgency)
SELECT * FROM (VALUES
  ('2型糖尿病', '视力模糊/飞蚊症突发', '糖尿病视网膜病变', '立即眼科就诊', 'HIGH'),
  ('2型糖尿病', '足部感觉异常/伤口不愈', '糖尿病足', '立即外科就诊', 'HIGH'),
  ('2型糖尿病', '心悸/出汗/手抖/饥饿感', '低血糖', '即时补糖并就医', 'HIGH'),
  ('2型糖尿病', '多尿/多饮/乏力加重/意识模糊', '糖尿病酮症酸中毒', '立即急诊', 'HIGH'),
  ('高血压', '剧烈头痛/呕吐/视物模糊', '高血压危象', '立即急诊', 'HIGH'),
  ('高血压', '胸痛/胸闷/大汗', '心肌梗死/主动脉夹层', '立即急诊（黄金120分钟）', 'HIGH'),
  ('高血压', '肢体麻木/言语不清/面瘫', '脑卒中', '立即急诊（黄金3小时）', 'HIGH'),
  ('冠心病', '持续胸痛>15分钟/含服硝酸甘油不缓解', '急性心肌梗死', '立即急诊（黄金120分钟）', 'HIGH'),
  ('冠心病', '夜间阵发呼吸困难/不能平卧', '心力衰竭', '心内科就诊', 'HIGH'),
  ('哮喘', '呼吸困难加重/讲话困难/嗜睡', '哮喘持续状态', '立即急诊', 'HIGH'),
  ('慢性肾病', '尿量骤减/水肿加重', '肾功能急性恶化', '立即肾内科', 'HIGH'),
  ('慢性肾病', '呼吸困难/不能平卧', '心衰/容量超负荷', '立即急诊', 'HIGH')
) AS seed(diagnosis_keyword, signal_symptom, complication, action_advice, urgency)
WHERE NOT EXISTS (SELECT 1 FROM complication_signal);

INSERT INTO recheck_window (diagnosis_keyword, item, timing, chrono_type, advice)
SELECT * FROM (VALUES
  ('2型糖尿病', '肝肾功能+空腹血糖', '服药2周后', 'PERIODIC', '二甲双胍起始治疗后必查'),
  ('2型糖尿病', '糖化血红蛋白(HbA1c)', '3个月后', 'PERIODIC', '评估血糖长期控制'),
  ('2型糖尿病', '眼底/足部/尿微量白蛋白', '每年', 'PERIODIC', '并发症筛查'),
  ('高血压', '血压复查', '服药2周后', 'PERIODIC', '评估降压效果'),
  ('高血压', '肝肾功能+电解质', '1-3个月后', 'PERIODIC', 'ACEI/利尿剂监测'),
  ('高血压', '心电图/心脏超声', '每年', 'PERIODIC', '靶器官损害评估'),
  ('冠心病', '症状复查+心电图', '服药1-2周后', 'PERIODIC', '评估治疗反应'),
  ('华法林', 'INR凝血指标', '服药3-5天后', 'PERIODIC', '调整剂量必查'),
  ('华法林', 'INR凝血指标', '稳定后每月', 'PERIODIC', '稳定期监测')
) AS seed(diagnosis_keyword, item, timing, chrono_type, advice)
WHERE NOT EXISTS (SELECT 1 FROM recheck_window);

INSERT INTO chrono_rule (diagnosis_keyword, chrono_type, event, trigger_time, action, start_hour, offset_days, period_days, target_month)
SELECT * FROM (VALUES
  ('冠心病', 'WINDOW', '心梗黄金救治窗口', '胸痛发作后120分钟内', '即时高优先级触达并引导急诊', NULL::INT, NULL::INT, NULL::INT, NULL::INT),
  ('2型糖尿病', 'RHYTHM', '夜间0-3点低血糖高发', '凌晨0-3点', '主动询问患者状态', 0, NULL, NULL, NULL),
  ('高血压', 'RHYTHM', '凌晨血压晨峰', '凌晨4-6点', '主动询问晨起血压', 4, NULL, NULL, NULL),
  ('哮喘', 'RHYTHM', '夜间哮喘发作高峰', '凌晨3-5点', '主动询问呼吸状态', 3, NULL, NULL, NULL),
  ('2型糖尿病', 'PERIODIC', '服药2周后复查肝肾功能', '服药后第14天', '主动提醒复查', NULL, 14, NULL, NULL),
  ('2型糖尿病', 'PERIODIC', '3个月后查糖化血红蛋白', '诊断后第90天', '主动提醒复查', NULL, 90, NULL, NULL),
  ('高血压', 'PERIODIC', '服药2周后血压复查', '服药后第14天', '主动提醒复查', NULL, 14, NULL, NULL),
  ('华法林', 'PERIODIC', '每月复查INR', '稳定后每月', '主动提醒复查INR', NULL, 3, 30, NULL),
  ('2型糖尿病', 'SEASONAL', '换季血糖波动', '秋冬换季', '主动提醒血糖监测', NULL, NULL, NULL, 9),
  ('高血压', 'SEASONAL', '秋冬血压升高', '入秋/入冬', '主动提醒增加监测频次', NULL, NULL, NULL, 9),
  ('哮喘', 'SEASONAL', '春季花粉诱发', '春季花粉季', '主动提醒预防用药', NULL, NULL, NULL, 3)
) AS seed(diagnosis_keyword, chrono_type, event, trigger_time, action, start_hour, offset_days, period_days, target_month)
WHERE NOT EXISTS (SELECT 1 FROM chrono_rule);

INSERT INTO department (id, code, name, description) VALUES
  (1, 'CARDIOLOGY', '心内科', '胸痛、心悸、高血压等心血管疾病诊疗科室'),
  (2, 'GENERAL', '全科门诊', '常见轻症初诊、复诊和健康咨询'),
  (3, 'RESPIRATORY', '呼吸内科', '咳嗽、哮喘、肺部感染等呼吸系统疾病诊疗')
ON CONFLICT (id) DO NOTHING;

INSERT INTO doctor (id, name, phone, password_hash, department_id, title, specialty, status) VALUES
  (1, '张医生', '13900000001', '{sha256}8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 1, '主任医师', '胸痛、心悸、高血压', 'ENABLED'),
  (2, '李医生', '13900000002', '{sha256}8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 2, '主治医师', '发热、咽痛、腹泻、皮肤过敏', 'ENABLED'),
  (3, '王医生', '13900000003', '{sha256}8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 3, '副主任医师', '咳嗽、哮喘、肺部感染', 'ENABLED')
ON CONFLICT (phone) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  department_id = EXCLUDED.department_id,
  title = EXCLUDED.title,
  specialty = EXCLUDED.specialty,
  status = EXCLUDED.status;

INSERT INTO patient (id, name, phone, password_hash, gender, age, allergy_history, past_history) VALUES
  (1, '测试患者', '13800000001', '{sha256}8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'FEMALE', 21, '无明确药物过敏史', '无特殊既往史')
ON CONFLICT (phone) DO UPDATE SET
  name = EXCLUDED.name,
  password_hash = EXCLUDED.password_hash,
  gender = EXCLUDED.gender,
  age = EXCLUDED.age,
  allergy_history = EXCLUDED.allergy_history,
  past_history = EXCLUDED.past_history;

INSERT INTO admin_user (id, username, password_hash, name, status) VALUES
  (1, 'admin', '{sha256}8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', '系统管理员', 'ENABLED')
ON CONFLICT (username) DO UPDATE SET
  password_hash = EXCLUDED.password_hash,
  name = EXCLUDED.name,
  status = EXCLUDED.status;

INSERT INTO drug (id, name, specification, contraindication, interaction_rule, status) VALUES
  (1, '阿司匹林', '100mg', '活动性出血禁用', '与抗凝药同用时出血风险升高', 'ENABLED'),
  (2, '对乙酰氨基酚', '0.5g', '严重肝功能不全慎用', '避免与其他含同成分复方药重复使用', 'ENABLED'),
  (3, '氯雷他定', '10mg', '对本品过敏禁用', '与强效 CYP3A4 抑制剂合用需谨慎', 'ENABLED'),
  (4, '阿莫西林', '0.25g', '青霉素过敏禁用', '与别嘌醇合用皮疹风险增加', 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO prompt_template (id, task_type, department_code, template_name, template_content, output_schema, version, enabled) VALUES
  (1, 'TRIAGE', 'GENERAL', 'GENERAL_TRIAGE_v1', '你是医院预分诊助手。根据患者主诉、症状、年龄、性别、过敏史和既往史推荐科室、医生方向、紧急程度、置信度和推理说明；不确定时说明需人工复核，不要编造医生 ID。', '{"type":"object","required":["recommendedDepartment","departmentCode","recommendedDoctorDirection","urgencyLevel","confidence","recommendedDoctorIds","reason"]}', 'v1', TRUE),
  (2, 'MEDICAL_RECORD', 'GENERAL', 'GENERAL_MEDICAL_RECORD_v1', '你是医生病历助手。根据真实问诊文本、患者信息、挂号信息和医生信息生成结构化病历，必须包含主诉、现病史、既往史、查体、初步诊断、处理建议和 SOAP 内容；不得忽略医生输入。', '{"type":"object","required":["chiefComplaint","presentIllness","pastHistory","physicalExam","diagnosis","treatmentAdvice","soapContent"]}', 'v1', TRUE),
  (3, 'PRESCRIPTION_CHECK', 'GENERAL', 'GENERAL_PRESCRIPTION_CHECK_v1', '你是处方安全审核助手。根据诊断、患者基本信息、过敏史/既往史、药品名称、剂量、用法、频次识别风险等级、风险说明、相互作用、禁忌症和调整建议；不要只按药品名给出固定结论。', '{"type":"object","required":["riskLevel","riskDescription","suggestions","interactions","contraindications","adjustmentSuggestions"]}', 'v1', TRUE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO knowledge_entry (id, title, symptoms, risk_signals, advice, department_code, status) VALUES
  (1, '普通感冒', '鼻塞、流涕、咽痛、低热、轻微咳嗽', '持续高热、呼吸困难、胸痛、意识异常', '注意休息和补液，症状加重或超过三天建议线下就诊。', 'GENERAL', 'ENABLED'),
  (2, '急性腹泻', '腹泻、腹痛、恶心、轻度乏力', '便血、严重脱水、持续高热、剧烈腹痛', '补液和清淡饮食，出现危险信号时及时就医。', 'GENERAL', 'ENABLED'),
  (3, '胸痛待查', '胸痛、胸闷、心悸、活动后气短', '压榨样胸痛、出冷汗、晕厥、持续不缓解', '出现危险信号时立即急诊；普通胸闷建议心内科评估。', 'CARDIOLOGY', 'ENABLED'),
  (4, '急性咳嗽', '咳嗽、咽痒、少量白痰', '咯血、呼吸困难、高热不退、血氧下降', '保持饮水和休息，若持续超过一周或伴危险信号建议呼吸内科就诊。', 'RESPIRATORY', 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO system_dict (id, dict_type, dict_key, dict_value, sort, status) VALUES
  (1, 'REGISTRATION_STATUS', 'CREATED', '已预约', 1, 'ENABLED'),
  (2, 'REGISTRATION_STATUS', 'CANCELLED', '已取消', 2, 'ENABLED'),
  (3, 'TRIAGE_STATUS', 'AI_RECOMMENDED', 'AI 已推荐', 1, 'ENABLED'),
  (4, 'TRIAGE_STATUS', 'ASSIGNED', '已分配医生', 2, 'ENABLED'),
  (5, 'TRIAGE_STATUS', 'CLOSED', '已关闭', 3, 'ENABLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO doctor_schedule (id, doctor_id, department_id, work_date, time_range, capacity, status) VALUES
  (1, 2, 2, CURRENT_DATE + 1, '09:00-12:00', 12, 'PUBLISHED'),
  (2, 1, 1, CURRENT_DATE + 1, '14:00-17:00', 8, 'PUBLISHED'),
  (3, 3, 3, CURRENT_DATE + 2, '09:00-12:00', 10, 'PUBLISHED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO appointment_slot (id, schedule_id, doctor_id, department_id, start_time, end_time, capacity, remaining_capacity, status) VALUES
  (1, 1, 2, 2, CURRENT_DATE + INTERVAL '1 day 9 hours', CURRENT_DATE + INTERVAL '1 day 12 hours', 12, 12, 'AVAILABLE'),
  (2, 2, 1, 1, CURRENT_DATE + INTERVAL '1 day 14 hours', CURRENT_DATE + INTERVAL '1 day 17 hours', 8, 8, 'AVAILABLE'),
  (3, 3, 3, 3, CURRENT_DATE + INTERVAL '2 day 9 hours', CURRENT_DATE + INTERVAL '2 day 12 hours', 10, 10, 'AVAILABLE')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('department', 'id'), COALESCE((SELECT MAX(id) FROM department), 1));
SELECT setval(pg_get_serial_sequence('doctor', 'id'), COALESCE((SELECT MAX(id) FROM doctor), 1));
SELECT setval(pg_get_serial_sequence('patient', 'id'), COALESCE((SELECT MAX(id) FROM patient), 1));
SELECT setval(pg_get_serial_sequence('admin_user', 'id'), COALESCE((SELECT MAX(id) FROM admin_user), 1));
SELECT setval(pg_get_serial_sequence('drug', 'id'), COALESCE((SELECT MAX(id) FROM drug), 1));
SELECT setval(pg_get_serial_sequence('prompt_template', 'id'), COALESCE((SELECT MAX(id) FROM prompt_template), 1));
SELECT setval(pg_get_serial_sequence('knowledge_entry', 'id'), COALESCE((SELECT MAX(id) FROM knowledge_entry), 1));
SELECT setval(pg_get_serial_sequence('system_dict', 'id'), COALESCE((SELECT MAX(id) FROM system_dict), 1));
SELECT setval(pg_get_serial_sequence('doctor_schedule', 'id'), COALESCE((SELECT MAX(id) FROM doctor_schedule), 1));
SELECT setval(pg_get_serial_sequence('appointment_slot', 'id'), COALESCE((SELECT MAX(id) FROM appointment_slot), 1));
SELECT setval(pg_get_serial_sequence('ai_schedule_suggestion', 'id'), COALESCE((SELECT MAX(id) FROM ai_schedule_suggestion), 1));
